### PR TITLE
Adds support to Julia 1.0

### PR DESCRIPTION
**Pull request by fernandogelin**
# Upgrades code to comply with Julia 1.0

## Types of changes

This PR implements the following changes:

* [ ] :sparkles: New feature (A non-breaking change which adds functionality).
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [x] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :clipboard: Additional detail

- One caveat is that BioTools depends on BioAlignment, which has a master branch working and passing tests but has not been tagged yet. We should wait until BioAlignments is tagged and update the Manifest.toml file before merging this pull request. Just wanted to let you know that I've upgraded this package and the tests are passing.

- I was also having issues with tests not passing on Mac OS because of the BLAST installation using Homebrew. I changed the installation on Travis to use conda and it's now passing. 

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [ ] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [ ] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [x] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [x] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [x] :ok: All changes should be compatible with the latest stable version of Julia.
- [ ] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by fernandogelin** [comment]
@BenJWard Now that BioAlignments has been tagged, and tests on Windows are passing, I think this PR is ready.

**Comment by TransGirlCodes** [comment]
@fernandogelin Awesome, thanks for doing this! I'll merge this and then update some of the project files before cutting a new release :)

**Comment by fernandogelin** [comment]
hey @BenJWard can we tag a new release for BioTools? You mentioned you wanted to update some of the project files, I'm happy to help with that and tag the new release. Let me know. Thanks!

**Comment by TransGirlCodes** [comment]
@fernandogelin Absolutely, I'm just making sure the README and documentation renders properly this evening and then we can tag a new release.

**Pull request merged**
